apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: house-price-streamlit
  name: house-price-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price-streamlit
  template:
    metadata:
      labels:
        app: house-price-streamlit
    spec:
      containers:
      - image: cvenugopal2005/house-price-streamlit:latest
        name: house-price-streamlit
        ports:
        - containerPort: 8501
